### ISSUE TITLE
磁力链接似乎会被改

### ISSUE THREAD

**Issue by CK-Tex** [oneNorth7/LinkHelper#2]
nyaa.si上可以重现，磁力链接会被砍成只保留后边的tracker部分。

![image](https://user-images.githubusercontent.com/16620756/115183032-9a482c00-a10d-11eb-90d2-c79ef274bbab.png)
请看左下角链接部分。

**Comment by oneNorth7** [comment]
测试了一下发现净化链接的匹配规则有点问题，针对上述问题，可将脚本中的第898行
https://github.com/oneNorth7/LinkHelper/blob/e93f8e11fd80a13bc46454e364f72bd10f053fee/%E9%93%BE%E6%8E%A5%E5%8A%A9%E6%89%8B.user.js#L898

整行改为以下代码后保存（末尾的逗号别忽略了）：
`let reg = /((?:http|https|\/|\%2F)(?:.*?\?.+?=|.*?\?))((?:https?:\/\/|www\.|\/|\%2F)[\w_\-\.~\/\=\?&#%\+:]+|(?:\w[\w._-]+\.(?:com|cn|org|net|info|tv|cc|gov|edu))(?:\/[\w_\-\.~\/\=\?&#%\+:]*)?)/,`

请修改后测试并反馈是否还有问题，谢谢支持！！！

**Comment by CK-Tex** [comment]
嗯 好了
