### ISSUE TITLE
1688产品页面跳转反诈骗中心

### ISSUE THREAD

**Issue by kky5** [oneNorth7/LinkHelper#4]
1.随便打开一个1688的产品例如 https://detail.1688.com/offer/595165641375.html?spm=a2615.2177701.autotrace-_t_15878088286509_1_0_1_1587821005052.3.3adb15cbH6iLvy

2.底部的“买家还在看”中的链接

3.被净化后的链接点击会跳转反诈骗中心http://www.js96110.com.cn

**Comment by oneNorth7** [comment]
可在1688产品页面使用脚本菜单`添加例外域名`将域名`detail.1688.com`添加到配置里，
之后刷新页面就可以了，已将此域名加入代码的例外域名名单，感谢使用和反馈！
