### ISSUE TITLE
百度以图搜图的搜索结果全部无法打开

### ISSUE THREAD

**Issue by XZ1314XZ** [oneNorth7/LinkHelper#7]
百度以图搜图的结果的所有图片域名为：graph.baidu.com。使用该脚本，会导致所有图片链接重定向到http://mms2.baidu.com/it/u=xxxxxxxxxxx的错误网址。知识水平有限，在代码中找不到对该域名净化的片段，望作者能够解决这个bug，同时希望增加白名单，以防止类似的网站被错误重定向

**Comment by oneNorth7** [comment]
可以参考下这个反馈配置一下
https://greasyfork.org/zh-CN/scripts/422773-%E9%93%BE%E6%8E%A5%E5%8A%A9%E6%89%8B/discussions/107291
